### ISSUE TITLE
Stripe plugin not compatible - fields for credit card payment will not be created. 

### ISSUE THREAD

**Issue by hiro-git-hub** [8mylez/EmzBiancoTheme#46]
![bildschirmfoto vom 2019-01-09 15-57-43](https://user-images.githubusercontent.com/22772200/50907393-8a6a1980-1427-11e9-8789-2e2f908f89b8.png)
![bildschirmfoto vom 2019-01-09 15-58-29](https://user-images.githubusercontent.com/22772200/50907405-93f38180-1427-11e9-88d1-258ae3f3fda3.png)

**Comment by subzer047** [comment]
This problem is fixed with version 1.2.3 in this PR https://github.com/8mylez/EmzBiancoTheme/pull/54

**Comment by hiro-git-hub** [comment]
Hey, thank you for fixing it so fast! I still have some problems with variant articles and 8Mylez Hover Classic and Premium shopping world elements. You can find a more accurate description in the issues.
