### ISSUE TITLE
Configuration of classic and elegance hover elements in backend is not possible

### ISSUE THREAD

**Issue by hiro-git-hub** [8mylez/EmzBiancoTheme#57]
It seems like an ExtJs Error that happens, after clicking the "edit" symbol of the elements. Tried to set the the xtype to "base" so editing is possible, but functionality won't work. 

![bildschirmfoto vom 2019-01-18 08-21-40](https://user-images.githubusercontent.com/22772200/51371595-e6553200-1afa-11e9-9842-d207f786b42b.png)

**Comment by subzer047** [comment]
This should be fixed if you clear the cache full
could you please try this?
Thanks

**Comment by hiro-git-hub** [comment]
Hey, i installed Theme Version 1.3.0 and this fixed the other issue with the variant articles. I cleared the cache full and reinstalled the theme, but the problem persists anyway. I also tried to delete production folder in var/cache but this did not worked too.

**Comment by subzer047** [comment]
One more Idea would be do delete the cache from the console in shopware

If this doesn't help could you please tell me which Browser and OS you're using?

**Comment by hiro-git-hub** [comment]
Cleared Cache with console and tried it with firefox, chrome and chromium on Linux Mint 19 Cinnamon. Maybe this Screenshot could help you out?! 
![bildschirmfoto vom 2019-01-26 20-33-33](https://user-images.githubusercontent.com/22772200/51791855-fbd8f480-21a9-11e9-8433-a73b7d429e51.png)

**Comment by subzer047** [comment]
Hi,
i talked with the pm and it seems that the backend elements shouldn't be merged.
We're going to remove them out of the theme.

I'm sorry for the circumstances.
